export type {
  AddWorkspaceInput,
  ConnectionFailure,
  ConnectionPhase,
  ConnectionState,
  CreateSessionInput,
  EnvironmentClient,
  EnvironmentCommandName,
  EnvironmentCommands,
  EnvironmentState,
  HydrationState,
  InterruptTurnInput,
  ListSessionsInput,
  LoadSessionHistoryInput,
  SessionHistoryPage,
  SessionListPage,
  PendingInteraction,
  ReasoningEntry,
  RespondToInteractionInput,
  SendTurnInput,
  SessionStatus,
  SessionSummary,
  ThreadState,
  ThreadTarget,
  ToolState,
  TurnFailure,
  TurnNotice,
  Unsubscribe,
} from './types'
export { EnvironmentClientError, isEnvironmentClientError } from './errors'
export {
  applyActiveSession,
  applyActiveThread,
  applyConnection,
  applyEnvironment,
  applyEvent,
  applyInteractionResolved,
  applySessionCreated,
  applySessionHistory,
  applySessionList,
  applySessionOpen,
  applySessionRemoved,
  applySessionTitle,
  applySnapshot,
  applyThreadHydration,
  applyTurnStarted,
  applyWorkspaceList,
  applyWorkspaceRemoved,
  createInitialState,
  createThreadState,
  deriveSessionStatus,
  selectActiveSession,
  selectActiveThread,
  selectActiveTurn,
  selectConnection,
  selectPendingInteractions,
  selectSessionList,
  selectWorkspaces,
  shallowEqualArray,
} from './state'
export { createEnvironmentStore, type EnvironmentStore } from './store'
export {
  pageSessionSummaries,
  pageThreadMessages,
  resolvePageLimit,
  sessionListCursorOf,
} from './pagination'
export { WIRE_COMMANDS, type WireCommandName } from './wire'
export {
  createMockEnvironmentClient,
  type MockCommandCall,
  type MockEnvironmentClient,
  type MockEnvironmentClientOptions,
  type MockSeed,
  type MockSeedSession,
  type MockTurnContext,
  type MockTurnTarget,
} from './mock'
export {
  createWebSocketEnvironmentClient,
  DEFAULT_RECONNECT,
  type ReconnectPolicy,
  type WebSocketConstructor,
  type WebSocketEnvironmentClientOptions,
  type WebSocketLike,
} from './websocket'
