/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ChatRouteImport } from './routes/_chat'
import { Route as PairRouteImport } from './routes/pair'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ChatIndexRouteImport } from './routes/_chat/index'
import { Route as PlaygroundConnectionRouteImport } from './routes/playground.connection'
import { Route as ChatDraftsDraftIdRouteImport } from './routes/_chat/drafts.$draftId'
import { Route as ChatSessionsSessionIdRouteImport } from './routes/_chat/sessions.$sessionId'

const ChatRoute = ChatRouteImport.update({
  id: '/_chat',
  getParentRoute: () => rootRouteImport,
} as any)
const PairRoute = PairRouteImport.update({
  id: '/pair',
  path: '/pair',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChatRoute,
} as any)
const PlaygroundConnectionRoute = PlaygroundConnectionRouteImport.update({
  id: '/playground/connection',
  path: '/playground/connection',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatDraftsDraftIdRoute = ChatDraftsDraftIdRouteImport.update({
  id: '/drafts/$draftId',
  path: '/drafts/$draftId',
  getParentRoute: () => ChatRoute,
} as any)
const ChatSessionsSessionIdRoute = ChatSessionsSessionIdRouteImport.update({
  id: '/sessions/$sessionId',
  path: '/sessions/$sessionId',
  getParentRoute: () => ChatRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ChatIndexRoute
  '/pair': typeof PairRoute
  '/settings': typeof SettingsRoute
  '/playground/connection': typeof PlaygroundConnectionRoute
  '/drafts/$draftId': typeof ChatDraftsDraftIdRoute
  '/sessions/$sessionId': typeof ChatSessionsSessionIdRoute
}
export interface FileRoutesByTo {
  '/pair': typeof PairRoute
  '/settings': typeof SettingsRoute
  '/playground/connection': typeof PlaygroundConnectionRoute
  '/': typeof ChatIndexRoute
  '/drafts/$draftId': typeof ChatDraftsDraftIdRoute
  '/sessions/$sessionId': typeof ChatSessionsSessionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_chat': typeof ChatRouteWithChildren
  '/pair': typeof PairRoute
  '/settings': typeof SettingsRoute
  '/playground/connection': typeof PlaygroundConnectionRoute
  '/_chat/': typeof ChatIndexRoute
  '/_chat/drafts/$draftId': typeof ChatDraftsDraftIdRoute
  '/_chat/sessions/$sessionId': typeof ChatSessionsSessionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/pair'
    | '/settings'
    | '/playground/connection'
    | '/drafts/$draftId'
    | '/sessions/$sessionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/pair'
    | '/settings'
    | '/playground/connection'
    | '/'
    | '/drafts/$draftId'
    | '/sessions/$sessionId'
  id:
    | '__root__'
    | '/_chat'
    | '/pair'
    | '/settings'
    | '/playground/connection'
    | '/_chat/'
    | '/_chat/drafts/$draftId'
    | '/_chat/sessions/$sessionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ChatRoute: typeof ChatRouteWithChildren
  PairRoute: typeof PairRoute
  SettingsRoute: typeof SettingsRoute
  PlaygroundConnectionRoute: typeof PlaygroundConnectionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_chat': {
      id: '/_chat'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pair': {
      id: '/pair'
      path: '/pair'
      fullPath: '/pair'
      preLoaderRoute: typeof PairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_chat/': {
      id: '/_chat/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof ChatRoute
    }
    '/playground/connection': {
      id: '/playground/connection'
      path: '/playground/connection'
      fullPath: '/playground/connection'
      preLoaderRoute: typeof PlaygroundConnectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_chat/drafts/$draftId': {
      id: '/_chat/drafts/$draftId'
      path: '/drafts/$draftId'
      fullPath: '/drafts/$draftId'
      preLoaderRoute: typeof ChatDraftsDraftIdRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/sessions/$sessionId': {
      id: '/_chat/sessions/$sessionId'
      path: '/sessions/$sessionId'
      fullPath: '/sessions/$sessionId'
      preLoaderRoute: typeof ChatSessionsSessionIdRouteImport
      parentRoute: typeof ChatRoute
    }
  }
}

interface ChatRouteChildren {
  ChatIndexRoute: typeof ChatIndexRoute
  ChatDraftsDraftIdRoute: typeof ChatDraftsDraftIdRoute
  ChatSessionsSessionIdRoute: typeof ChatSessionsSessionIdRoute
}

const ChatRouteChildren: ChatRouteChildren = {
  ChatIndexRoute: ChatIndexRoute,
  ChatDraftsDraftIdRoute: ChatDraftsDraftIdRoute,
  ChatSessionsSessionIdRoute: ChatSessionsSessionIdRoute,
}

const ChatRouteWithChildren = ChatRoute._addFileChildren(ChatRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ChatRoute: ChatRouteWithChildren,
  PairRoute: PairRoute,
  SettingsRoute: SettingsRoute,
  PlaygroundConnectionRoute: PlaygroundConnectionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
